const express = require('express');
const router = express.Router();
const fileController = require('../controller/files.controller');
router.post('/api/files',fileController.createNewFileForUser);
router.put('/api/files',fileController.addMembers);
router.get('/api/files',fileController.getFilesForUser);
router.get('/api/files/test',fileController.test);
router.post('/api/members',fileController.removeMembers);
router.post('/api/files/download',fileController.getFile);
router.get('/api/files/shared',fileController.getSharedFile);
router.post('/api/files/delete',fileController.deleteFileForUser);
module.exports=router;